# Generated by Django 2.2.27 on 2023-01-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=4),
        ),
    ]
