# Generated by Django 2.2.27 on 2023-01-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_types',
            field=models.CharField(choices=[('apartments', 'Apartments'), ('penthouses', 'Penthouses'), ('houses', 'Houses'), ('villas', 'Villas'), ('residential_plots', 'Residential Plots')], default='apartments', max_length=17),
        ),
    ]
