# Generated by Django 2.2.27 on 2023-01-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20230128_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='property_types',
            new_name='property_type',
        ),
    ]
