# Generated by Django 2.2.27 on 2023-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20230128_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartments', 'Apartments'), ('penthouses', 'Penthouses'), ('houses', 'Houses'), ('villas', 'Villas'), ('residential_plots', 'Residential Plots')], default='apartments', max_length=17),
        ),
        migrations.AddField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=4),
        ),
    ]
