# Generated by Django 2.2.27 on 2023-01-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20230128_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_6',
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
