# Generated by Django 2.2.27 on 2023-02-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20230130_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartments', 'Apartments'), ('penthouses', 'Penthouses'), ('houses', 'Houses'), ('villas', 'Villas'), ('residential_plots', 'Residential Plots')], max_length=17),
        ),
        migrations.AlterField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent')], max_length=4),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
